[package]
name = "hello_world"
version = "0.1.0"
authors = ["bdagdeviren"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zip = "0.5.2"
reqwest = "0.9.19"
rocket = "0.4.2"
